buildscript {
    ext.kotlin_version = '2.0.0'

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    id 'java'
}

apply plugin: "kotlin"

group 'com.agmtopy'
version '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

compileKotlin {
    kotlinOptions {
        jvmTarget = '21'
    }
}

compileTestKotlin {
    kotlinOptions {
        jvmTarget = '21'
    }
}

allprojects{
    repositories {
        mavenCentral()
    }
}

dependencies {
    implementation "commons-cli:commons-cli:1.4"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0"

    testImplementation('org.junit.jupiter:junit-jupiter:5.5.2')
}

test {
    useJUnitPlatform()
}
