plugins {
    id 'java'
    id 'kotlin'
}

group 'com.agmtopy'
version '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

compileKotlin {
    kotlinOptions {
        jvmTarget = '21'
    }
}

compileTestKotlin {
    kotlinOptions {
        jvmTarget = '21'
    }
}

dependencies {
    //第三方jar
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0-RC"
}